### ISSUE TITLE
Consider remove the personal information in code.

### ISSUE THREAD

**Issue by M1andy** [bjzhb666/GS-LoRA#3]
There are some personal information in code need to remove!

- wandb login key. (train/train_own_forget.py, train/train_own_forget_cl.py, train/train_own.py)
- bash scripts contains personal paths. (all bash scripts under scripts/)

**Comment by bjzhb666** [comment]
Thanks for your advice. I will do it later.

**Comment by bjzhb666** [comment]
Done!
