### ISSUE TITLE
Questions Regarding Baselines: SCRUB and SCRUB-S

### ISSUE THREAD

**Issue by ChengZe2005** [bjzhb666/GS-LoRA#8]
I have a question regarding the SCRUB and SCRUB-S implementations. In the scripts, I noticed the parameter --sgda_smoothing 0.1, which indicates that the script is set to run SCRUB-S. Could you please clarify how I can modify the parameters to run SCRUB instead? Can I just simply delete --sgda_smoothing 0.1？ Thank you!

**Comment by bjzhb666** [comment]
set it to 0
